# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.102.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Hugo for pages
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cp config.toml config_zccrs_com.toml
          sed -i '/\[params.gitalk\]/a\${{ secrets.HUGO_CONFIG_ZCCRS_COM }}' config_zccrs_com.toml
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --config config_zccrs_com.toml
          echo "zccrs.com" > ./public/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
      - name: Build with Hugo for vps
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          rm -rf ./public
          cp config.toml config_zcc_rs.toml
          sed -i '/\[params.gitalk\]/a\${{ secrets.HUGO_CONFIG_ZCC_RS }}' config_zcc_rs.toml
          hugo \
            --minify \
            --baseURL "https://zcc.rs/" \
            --config config_zcc_rs.toml
      - name: Deploy ssh key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.BLOG_DEPLOY_KEY }}
      - name: Scan public keys
        run: |
          ssh-keyscan zcc.rs >> ~/.ssh/known_hosts
      - name: Sync to vps
        run: |
          sudo apt install rsync
          rsync -av --delete ./public zccrs@zcc.rs:~/docker/caddy/data/blog

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
